--- 
name: fbook
extensions: 
- extension-name-here
- second-extension-name
bbver: 4.6
sdk: /Users/vlad/Documents/Projects/rhodes
version: 1.0
applog: rholog.txt
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
vendor: rhomobile
sdkversion: 1.5.1
iphone: 
  configuration: Debug
  sdk: iphonesimulator3.0
  codesignidentity: 
  provisionprofile: 
  entitlements: 
